### ISSUE TITLE
Pls change the player 🙏

### ISSUE THREAD

**Issue by buttlicker2** [sinnedpenguin/animeden#1]
And also pls add the thing where you double click the side to either skip 10 seconds or go back

**Comment by sinnedpenguin** [comment]
Hi. I think Artplayer works fine, but I'll check some other video players. As for the double click/tap, that's something I forgot to implement to be honest, I'll add that soon.

**Comment by sinnedpenguin** [comment]
Hi. I think Artplayer works fine, but I'll check some other video players. As for the double click/tap, that's something I forgot to implement to be honest. I'll add that soon.
